---

name: Bump version
on:
  workflow_call:
    inputs:
      secrets:
        github_token:
          required: true
  push:
    branches:
      - $default-branch
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.github_token }}
          release_branches: $default-branch
