---

name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  call_bump:
    uses: cornbuddy/github-reusable-workflows/.github/workflows/_bump-version.yml@develop
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
